// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image8;
extern void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image7;
extern void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel4;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Label1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

