// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image9;
extern void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Slider1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

