// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_try_png);    // assets/try.png
LV_IMG_DECLARE(ui_img_zsp1_png);    // assets/zsp1.png
LV_IMG_DECLARE(ui_img_zz_png);    // assets/zz.png
LV_IMG_DECLARE(ui_img_shache_png);    // assets/shache.png
LV_IMG_DECLARE(ui_img_youzxd_png);    // assets/youzxd.png
LV_IMG_DECLARE(ui_img_youmen_png);    // assets/youmen.png
LV_IMG_DECLARE(ui_img_zzxd_png);    // assets/zzxd.png
LV_IMG_DECLARE(ui_img_zhuangshi6_png);    // assets/zhuangshi6.png
LV_IMG_DECLARE(ui_img_zhuangshi4_png);    // assets/zhuangshi4.png
LV_IMG_DECLARE(ui_img_zhuangshi5_png);    // assets/zhuangshi5.png
LV_IMG_DECLARE(ui_img_zanting_png);    // assets/zanting.png
LV_IMG_DECLARE(ui_img_qianyishou_png);    // assets/qianyishou.png
LV_IMG_DECLARE(ui_img_img11_png);    // assets/img11.png

// FONTS
LV_FONT_DECLARE(ui_font_chinese);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
